repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
    - id: no-commit-to-branch
      args: ['--pattern', '^(?!((bugfix|build|docs|feat|refactor|dev|release)\/[a-zA-Z0-9\-\_]+)$).*']
    - id: end-of-file-fixer
    - id: trailing-whitespace
- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
    - id: isort
      args: ["--profile", "black", "--filter-files"]
- repo: https://github.com/psf/black
  rev: 22.6.0
  hooks:
    - id: black
      args: # arguments to configure black
        - --line-length=100
- repo: https://github.com/pycqa/flake8
  rev: 5.0.4
  hooks:
    - id: flake8
- repo: local
  hooks:
  - id: precommit-installed
    name: precommit-installed
    stages: [commit]
    entry: .venv/bin/pre-commit install --hook-type pre-commit --hook-type pre-push
    language: system
    pass_filenames: false
    always_run: true
- repo: local
  hooks:
  - id: pytest-check
    name: pytest
    stages: [push]
    types: [python]
    entry: .venv/bin/pytest -q tests/unit_tests -n 4
    language: system
    pass_filenames: false
    always_run: true
